# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Test Anvil

on:
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: "Log level"
    #     required: true
    #     default: "warning"
    #     type: choice
    #     options:
    #       - info
    #       - warning
    #       - debug
    #   tags:
    #     description: "Test scenario tags"
    #     required: false
    #     type: boolean
    #   environment:
    #     description: "Environment to run tests against"
    #     type: environment
    #     required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: anvil &
      - run: npm run test:anvil
